name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  verify:
    name: Verify Code
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.1

      - name: Run Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v22.0.0
        with:
          globs: '**/*.md'

      - name: Run PSScriptAnalyzer
        shell: powershell
        run: |
          $results = Invoke-ScriptAnalyzer -Path ".\winget-updater-core" -Recurse -Severity Error,Warning
          if ($results) {
              $results | Format-Table
              exit 1
          }
          Write-Host "PSScriptAnalyzer passed successfully."

  build:
    name: Build Installer and Create Release
    needs: verify
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Compile Inno Setup Script
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
        with:
          path: installer/setup.iss

      - name: Create Zip Archive
        shell: pwsh
        run: |
          Compress-Archive -Path install-winget-updater.bat, winget-updater-core, installer/version.isi -DestinationPath WinGet-Updater.zip

      - name: Create Draft Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2.5.0
        with:
          files: |
            installer/Output/WingetUpdaterSetup.exe
            WinGet-Updater.zip
          draft: true
          generate_release_notes: true
